FROM centos:6
COPY op5repos.repo /etc/yum.repos.d/
COPY RPM-GPG-KEY-op5 /etc/pki/rpm-gpg/

RUN yum install --assumeyes vim yum-utils git

RUN yum install --assumeyes autoconf automake libtool gcc gdb

RUN yum install --assumeyes glib2-devel check-devel libdbi-devel op5-naemon-devel gperf

RUN yum install --assumeyes naemon monitor-livestatus libdbi-drivers libdbi libdbi-dbd-mysql mysql-libs

RUN yum install --assumeyes ruby20-devel rubygem20-multi_json mysql mysql-server mysql-devel nap

RUN yum install -y op5-monitor

#RUN gem2.0 install --no-document cucumber:1.3.6 nokogiri:1.6.0 rack:1.6.5 capybara:2.1.0 poltergeist:1.11.0 rspec:2.14.1 parallel_tests syntax:1.0.0

RUN rm -r /opt/monitor/etc/mconf/merlin.cfg

RUN yum update --assumeyes

CMD service mysqld restart && service httpd restart && mon restart && service synergy restart && bash -il && not-date se.pool.ntp.org
